import fs from "fs";
import path from "path";
import type { Plugin } from "vite";

function walk(dir: string): string[] {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    let files: string[] = [];
    for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) files = files.concat(walk(full));
        else if (entry.isFile() && /[.]tsx$|[.]jsx$|[.]mdx$|[.]ts$/.test(entry.name)) files.push(full);
    }
    return files;
}

function generateForRoutes(appDir: string) {
    const routesDir = path.join(appDir, "routes");
    if (!fs.existsSync(routesDir)) return;

    const files = walk(routesDir)
        .map((f) => path.relative(appDir, f).replaceAll(path.sep, "/"))
        .sort();

    const literalList = files.map((f) => `  \"${f}\",`).join("\n");

    const content = `// This file is generated by vite-plugin-route-types.ts — do not edit
export const routeFileList = [
${literalList}
] as const;

export type RouteFilePath = typeof routeFileList[number];
`;

    const outFile = path.join(appDir, "route-files.d.ts");
    try {
        const prev = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8") : null;
        if (prev === content) return; // avoid touching file if nothing changed
        fs.writeFileSync(outFile, content, "utf8");
    } catch (e) {
        // ignore write errors
    }
}

export default function routeTypesPlugin(): Plugin {
    const appDir = path.join(process.cwd(), "app");

    return {
        name: "vite-plugin-route-types",
        configureServer(server) {
            // generate initially
            generateForRoutes(appDir);

            const reload = async (filePath: string) => {
                if (!filePath) return;
                // only react to changes inside app/routes
                const normalized = filePath.replaceAll(path.sep, "/");
                if (normalized.includes("/app/routes/") || normalized.startsWith("app/routes/")) {
                    try {
                        generateForRoutes(appDir);
                        // invalidate any Vite module graph entries for the changed file
                        try {
                            // prefer getModulesByFile if available
                            // @ts-ignore
                            const mods = server.moduleGraph.getModulesByFile?.(filePath) ?? new Set();
                            for (const m of mods) {
                                try {
                                    server.moduleGraph.invalidateModule(m);
                                } catch { }
                            }

                            // As a fallback / additional safety, invalidate any file keys that include /app/routes/
                            // @ts-ignore
                            const fileToModules = server.moduleGraph.fileToModules;
                            if (fileToModules && typeof fileToModules[Symbol.iterator] === 'function') {
                                for (const [file, modSet] of fileToModules as any) {
                                    if (typeof file === 'string' && file.includes('/app/routes/')) {
                                        for (const m of modSet) {
                                            try {
                                                server.moduleGraph.invalidateModule(m);
                                            } catch { }
                                        }
                                    }
                                }
                            }
                        } catch (err) {
                            // ignore
                        }

                        server.ws.send({ type: "full-reload" });
                    } catch (e) {
                        // ignore
                    }
                }
            };

            server.watcher.on("add", reload);
            server.watcher.on("unlink", reload);
            server.watcher.on("change", reload);
        },
        buildStart() {
            // also generate during build
            generateForRoutes(appDir);
        },
    };
}
