// This file is generated by vite-plugin-route-types.ts — do not edit
export const routeFileList = [
  "routes/_/_landing._index/route.tsx",
  "routes/_/test/route.tsx",
  "routes/_blog/_contents/test.mdx",
  "routes/_blog/layout.tsx",
  "routes/_blog/route.tsx",
  "routes/_utils/[robots.txt].tsx",
  "routes/_utils/blogs.[rss].ts",
  "routes/_utils/feed[.]json.tsx",
  "routes/_utils/route.tsx",
  "routes/_utils/sitemap[.]xml.tsx",
  "routes/auth/layout.tsx",
  "routes/auth/login.tsx",
  "routes/auth/signup.tsx",
  "routes/layout.tsx",
] as const;

export type RouteFilePath = typeof routeFileList[number];
