// This file is generated by vite-plugin-route-types.ts — do not edit
export const routeFileList = [
  "routes/_landing._index/route.tsx",
  "routes/auth/layout.tsx",
  "routes/auth/login.tsx",
  "routes/auth/signup.tsx",
  "routes/test.mdx",
] as const;

export type RouteFilePath = typeof routeFileList[number];
